# Generated by Django 4.2.3 on 2023-07-24 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TodoList",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="id"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                ("due_date", models.DateField(verbose_name="due_date")),
                (
                    "priority",
                    models.IntegerField(
                        choices=[(1, "Active"), (2, "Inactive"), (3, "Archived")],
                        default=3,
                        verbose_name="priority",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "To-Do"), (2, "In-Progress"), (3, "Completed")],
                        default=3,
                        verbose_name="status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created_at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated_at"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OperationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="timestamp"),
                ),
                ("action", models.CharField(max_length=100, verbose_name="action")),
                ("description", models.TextField(verbose_name="description")),
                (
                    "todo_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tasks.todolist"
                    ),
                ),
            ],
        ),
    ]
