# Generated by Django 4.2.3 on 2023-07-24 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="operationlog",
            name="changes",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="operationlog",
            name="action",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="operationlog", name="description", field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="operationlog",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
