# Generated by Django 4.2.3 on 2023-07-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_operationlog_changes_alter_operationlog_action_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todolist",
            name="priority",
            field=models.IntegerField(
                choices=[(1, "High"), (2, "Medium"), (3, "Low")],
                default=3,
                verbose_name="priority",
            ),
        ),
    ]
